<?php

namespace DesignPatterns\Creational\Builder;

// Product class

/**
 * The product class defines the type of the complex object that is to be generated by the builder pattern.
 */
class Laptop
{
    public $modelNumber;
    public $display;
    public $RAM;
    public $graphicCard;
    public $touchScreen;

    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            $this->$property = $value;
        }
    }

    public function __get($property)
    {
        if (property_exists($this, $property)) {
            return $this->$property;
        }
    }

    public function __toString()
    {
        $result = "\n------------- Laptop -------------\n";
        $result .= "Model Number\t: {$this->modelNumber}\n";
        $result .= "Display\t\t: {$this->display}\n";
        $result .= "RAM\t\t: {$this->RAM}\n";
        $result .= "Graphic Card\t: {$this->graphicCard}\n";
        $result .= "Touch Screen\t: {$this->touchScreen}\n";

        return $result;
    }
}
